added healthchecks to test step

diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -17,7 +17,7 @@ executors:
       _JAVA_OPTIONS: "-Xmx512m"
     docker:
       - image: cimg/openjdk:11.0
-      - image: rabbitmq:3
+      - image: rabbitmq:3-management
       - image: mongo:4
 
 
@@ -74,6 +74,43 @@ jobs:
           keys:
             - logreposit-api-{{ checksum "pom.xml" }}
             - logreposit-api-
+      - run:
+          name: Installing tools
+          command: |
+            cd ~
+            sudo apt-get -y update && sudo apt-get -y --allow-unauthenticated install curl mongodb-clients
+      - run:
+          name: Checking if MongoDB is available
+          command: |
+            available=1
+            for i in `seq 0 100`;
+            do
+                if echo 'db.runCommand("ping").ok' | mongo localhost:27017/test --quiet ; then
+                    available=0
+                    break
+                fi
+                sleep 1
+            done
+            if [[ ${available} -eq 1 ]]; then
+              echo "Couldn't connect to RabbitMQ"
+              exit 1
+            fi
+      - run:
+          name: Checking if RabbitMQ is available
+          command: |
+            available=1
+            for i in `seq 0 100`;
+            do
+                if curl -sS -u guest:guest -X GET http://127.0.0.1:15672/api/healthchecks/node ; then
+                    available=0
+                    break
+                fi
+                sleep 1
+            done
+            if [[ ${available} -eq 1 ]]; then
+              echo "Couldn't connect to RabbitMQ"
+              exit 1
+            fi
       - run:
           name: Enable Test Splitting
           command: |
